config/routes.rb
Pbook::Application.routes.draw do

    root                to: 'static_pages#home'
    match '/about',     to: 'static_pages#about'

    match '/signup',    to: 'users#new'
    match '/signin',    to: 'sessions#new'
    match '/signout',   to: 'sessions#destroy', via: :delete

    get "/profile", to: "users#profile"

    get 'user/:id/portfolio/:id', to: 'users#show#portfolios#show'

    get "users/get_init_data"
    get "users/get_week_totals"
    get "users/select_portfolio"
    get "users/create_portfolio"
    get "users/remove_portfolio"

    get "users/select_week"
    get "users/create_week"
    get "users/remove_week"

    get "users/update_week_date"
    get "users/update_week_value"
    get "users/update_week_free_cash"
    get "users/update_week_comment"
    get "users/update_table_cell"
    get "users/add_table_row"
    get "users/remove_table_row"
    
    get "traders/add_to_portfolio"
    get "traders/test_ajax"
    get "traders/test_get"
    post "traders/test_post"
    
    get "portfolios/show_portfolio_data"
    get "portfolios/hide_portfolio_data"

    resources :sessions,        only: [:new, :create, :destroy]
    resources :users
    resources :portfolios,      only: [:index, :show]
    resources :traders,         only: [:index]

end

app/views/layouts/_footer.html.erb
<footer class="footer">
	<small>
		pbook@gmail.com
	</small>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
	<div class="navbar-inner">
		<div> <!-- class="container" -->
			<%= link_to "pbook", root_path, id: "logo" %>
			<nav>
				<ul class="nav nav-pills pull-right">
					<li><%= link_to "О проекте", about_path %></li>

					<% if signed_in? %>
						<li id="fat-menu" class="dropdown">
							<a href="#" class="dropdown-toggle" data-toggle="dropdown">
								<%= current_user.name %> <b class="caret"></b>
							</a>
							<ul class="dropdown-menu dropdown-menu-right">
								<li><%= link_to "Профайл", profile_path %></li>
								<li><%= link_to "Настройки", edit_user_path(current_user) %></li>
								<li class="divider"></li>
								<li><%= link_to "Выход", signout_path, method: "delete" %></li>
							</ul>
						</li>
					<% else %>
						<li><%= link_to "Вход", signin_path %></li>
					<% end %>
				</ul>
			</nav>
		</div>
	</div>
</header>

app/views/layouts/_menu_block.html.erb
<button id="main_menu_button" class="btn btn-success">
	<%= link_to "Главная", root_path %>
</button>

<br/><br/>

<button id="traders_menu_button" class="btn btn-success">
	<%= link_to "Управл", traders_path %>
</button>

<br/><br/>

<button id="portfolios_menu_button" class="btn btn-success">
	<%= link_to "Портфели", portfolios_path %>
</button>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
		<title><%= full_title(yield(:title)) %></title>
		<%= stylesheet_link_tag    "application", :media => "all" %>
		<%= javascript_include_tag "application" %>
		<%= csrf_meta_tags %>
		<%= render 'layouts/shim' %>
	</head>

	<body>
		<%= render 'layouts/header' %>
		<div style="width:1050px; margin:0 auto; padding:10px;"> <!-- class="container" -->
			<% flash.each do |key, value| %>
				<%= content_tag(:div, value, class: "alert alert-#{key}") %>
				<!-- the same as -->
				<!-- <div class="alert alert-<%= key %>"><%= value %></div> -->
			<% end %>

			<div class="menu_block"> <!-- class="row menu_block" -->
				<aside class="span4">
					<section>
						<%= render 'layouts/menu_block' %>
					</section>
				</aside>
			</div>

			<section>
				<%= yield %>
			</section>

			<%= render 'layouts/footer' %>
			<%= debug(params) if Rails.env.development? %>
		</div>
	</body>
</html>